<?php if($this->_tokenizerEnabled() == '1'): ?>
<div class="tokenizer-authenticator-login">
    <div class="account-login">
        <form action="http://localhost/testsite/index.php/customer/account/loginPostTokenizer/" method="post" id="tokenizer login-form">

            <div class="<?php echo $this->_getColSet(); ?> tokenizer-authenticator-login-upper">
                <div class="<?php echo $this->_getDescCol(); ?> registered-users tokenizer-authenticator-login-upper-google">
                    <div class="content">
                        <h2><?php echo $this->__('Tokenizer Login'); ?></h2>
                        <p><?php echo $this->__('You can login using your Tokenizer account.'); ?></p>
                            <ul class="form-list">
                                <li>
                                    <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                                    <div class="input-box">
                                        <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                                    </div>
                                </li>
                                <li>
                                    <input type="text" id="login[tokenizer]" title="tokenizer" value="sadaaaa" readonly hidden/>
                                </li>
                            </ul>
                            <p class="required">* Required Fields</p>                       
                    </div>
                </div>
            </div>
            <div class="<?php echo $this->_getColSet(); ?> tokenizer-authenticator-login-lower">
                <div class="<?php echo $this->_getButtCol(); ?> tokenizer-authenticator-login-lower-google">
                    <div class="buttons-set">
                        <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="tokenizer-send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<?php endif; ?>